[2024-05-23T11:33:50.704+0000] {processor.py:156} INFO - Started process (PID=35) to work on /opt/airflow/dags/dag2.py
[2024-05-23T11:33:50.710+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dag2.py for tasks to queue
[2024-05-23T11:33:50.710+0000] {logging_mixin.py:117} INFO - [2024-05-23T11:33:50.710+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dag2.py
[2024-05-23T11:33:51.594+0000] {logging_mixin.py:117} INFO - [2024-05-23T11:33:51.591+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag2.py", line 10, in <module>
    from transform_script import transfrom
  File "/opt/airflow/dags/transform_script.py", line 2, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-05-23T11:33:51.595+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dag2.py
[2024-05-23T11:33:51.640+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dag2.py took 0.937 seconds
[2024-05-23T11:34:22.739+0000] {processor.py:156} INFO - Started process (PID=49) to work on /opt/airflow/dags/dag2.py
[2024-05-23T11:34:23.801+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dag2.py for tasks to queue
[2024-05-23T11:34:23.974+0000] {logging_mixin.py:117} INFO - [2024-05-23T11:34:23.973+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dag2.py
[2024-05-23T11:34:27.890+0000] {logging_mixin.py:117} INFO - [2024-05-23T11:34:27.888+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag2.py", line 10, in <module>
    from transform_script import transfrom
  File "/opt/airflow/dags/transform_script.py", line 2, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-05-23T11:34:27.891+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dag2.py
[2024-05-23T11:34:27.906+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dag2.py took 5.539 seconds
[2024-05-23T11:34:59.550+0000] {processor.py:156} INFO - Started process (PID=77) to work on /opt/airflow/dags/dag2.py
[2024-05-23T11:34:59.573+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dag2.py for tasks to queue
[2024-05-23T11:34:59.593+0000] {logging_mixin.py:117} INFO - [2024-05-23T11:34:59.593+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dag2.py
[2024-05-23T11:35:01.565+0000] {logging_mixin.py:117} INFO - [2024-05-23T11:35:01.557+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag2.py", line 10, in <module>
    from transform_script import transfrom
  File "/opt/airflow/dags/transform_script.py", line 2, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-05-23T11:35:01.567+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dag2.py
[2024-05-23T11:35:06.782+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dag2.py took 8.155 seconds
[2024-05-23T11:35:39.440+0000] {processor.py:156} INFO - Started process (PID=91) to work on /opt/airflow/dags/dag2.py
[2024-05-23T11:35:39.444+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dag2.py for tasks to queue
[2024-05-23T11:35:39.446+0000] {logging_mixin.py:117} INFO - [2024-05-23T11:35:39.445+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dag2.py
[2024-05-23T11:35:47.788+0000] {logging_mixin.py:117} INFO - [2024-05-23T11:35:47.780+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag2.py", line 10, in <module>
    from transform_script import transfrom
  File "/opt/airflow/dags/transform_script.py", line 2, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-05-23T11:35:47.790+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dag2.py
[2024-05-23T11:35:47.923+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dag2.py took 8.502 seconds
[2024-05-23T11:36:28.871+0000] {processor.py:156} INFO - Started process (PID=115) to work on /opt/airflow/dags/dag2.py
[2024-05-23T11:36:28.888+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dag2.py for tasks to queue
[2024-05-23T11:36:29.180+0000] {logging_mixin.py:117} INFO - [2024-05-23T11:36:28.903+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dag2.py
[2024-05-23T11:36:44.469+0000] {logging_mixin.py:117} INFO - [2024-05-23T11:36:44.453+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag2.py", line 10, in <module>
    from transform_script import transfrom
  File "/opt/airflow/dags/transform_script.py", line 2, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-05-23T11:36:44.474+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dag2.py
[2024-05-23T11:37:27.524+0000] {processor.py:156} INFO - Started process (PID=139) to work on /opt/airflow/dags/dag2.py
[2024-05-23T11:37:27.545+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dag2.py for tasks to queue
[2024-05-23T11:37:27.592+0000] {logging_mixin.py:117} INFO - [2024-05-23T11:37:27.572+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dag2.py
[2024-05-23T11:37:58.130+0000] {logging_mixin.py:117} INFO - [2024-05-23T11:37:57.902+0000] {timeout.py:68} ERROR - Process timed out, PID: 139
[2024-05-23T11:38:00.391+0000] {logging_mixin.py:117} INFO - [2024-05-23T11:37:58.435+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag2.py", line 9, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 73, in <module>
    from pandas.core.frame import DataFrame
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 129, in <module>
    from pandas.core import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 144, in <module>
    from pandas.core.window import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/window/__init__.py", line 1, in <module>
    from pandas.core.window.ewm import (  # noqa:F401
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/window/ewm.py", line 11, in <module>
    import pandas._libs.window.aggregations as window_aggregations
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag2.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.1/best-practices.html#reducing-dag-complexity, PID: 139
[2024-05-23T11:38:01.141+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dag2.py
