[2024-05-21T11:03:53.289+0000] {processor.py:156} INFO - Started process (PID=35) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:03:53.290+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:03:53.291+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:03:53.291+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:03:53.482+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:03:53.597+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:03:53.597+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:03:53.627+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:03:53.627+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:03:53.666+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 0.380 seconds
[2024-05-21T11:04:35.787+0000] {processor.py:156} INFO - Started process (PID=45) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:04:35.789+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:04:35.804+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:04:35.803+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:04:36.337+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:04:37.327+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:04:37.327+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:04:37.495+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:04:37.493+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:04:37.553+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 1.793 seconds
[2024-05-21T11:05:46.543+0000] {processor.py:156} INFO - Started process (PID=55) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:05:46.547+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:05:46.557+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:05:46.557+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:05:47.271+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:06:12.976+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:06:12.969+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:06:14.082+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:06:14.076+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:06:32.408+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 45.932 seconds
[2024-05-21T11:07:08.902+0000] {processor.py:156} INFO - Started process (PID=74) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:07:08.909+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:07:08.924+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:07:08.924+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:07:21.009+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:07:40.324+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:07:40.323+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:07:41.249+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:07:41.243+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:07:41.522+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 32.755 seconds
[2024-05-21T11:08:16.656+0000] {processor.py:156} INFO - Started process (PID=84) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:08:16.664+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:08:16.674+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:08:16.674+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:08:19.038+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:08:22.258+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:08:22.257+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:08:22.575+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:08:22.574+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:08:22.719+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 6.161 seconds
[2024-05-21T11:08:55.868+0000] {processor.py:156} INFO - Started process (PID=93) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:08:55.893+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:08:55.932+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:08:55.932+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:09:01.099+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:09:02.967+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:09:02.940+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:09:06.054+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:09:06.050+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:09:07.229+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 11.552 seconds
[2024-05-21T11:09:38.803+0000] {processor.py:156} INFO - Started process (PID=103) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:09:38.876+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:09:39.542+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:09:38.920+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:09:46.628+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:09:58.395+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:09:58.394+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:09:59.490+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:09:59.488+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:10:01.149+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 22.476 seconds
[2024-05-21T11:10:37.702+0000] {processor.py:156} INFO - Started process (PID=112) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:10:39.227+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:10:39.233+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:10:39.233+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:10:39.353+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:11:07.851+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:11:07.845+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:11:09.764+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:11:09.759+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:11:11.331+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 39.468 seconds
[2024-05-21T11:11:50.792+0000] {processor.py:156} INFO - Started process (PID=122) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:11:50.801+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:11:50.817+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:11:50.816+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:11:52.349+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:12:14.054+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:12:14.053+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:12:14.492+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:12:14.490+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:12:14.671+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 32.366 seconds
[2024-05-21T11:12:47.429+0000] {processor.py:156} INFO - Started process (PID=140) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:12:48.133+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:12:49.863+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:12:49.698+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:12:57.202+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:13:08.321+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:13:08.319+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:13:08.601+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:13:08.598+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:13:19.017+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 32.623 seconds
[2024-05-21T11:15:00.215+0000] {processor.py:156} INFO - Started process (PID=141) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:15:00.230+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:15:00.288+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:15:00.250+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:15:03.011+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:15:23.490+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:15:23.489+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:15:24.666+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:15:24.661+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:15:27.347+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 27.527 seconds
[2024-05-21T11:15:58.275+0000] {processor.py:156} INFO - Started process (PID=160) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:15:58.282+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:15:58.283+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:15:58.283+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:15:58.528+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:16:19.632+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:16:19.631+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:16:19.671+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:16:19.671+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:16:19.723+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 21.453 seconds
[2024-05-21T11:16:49.813+0000] {processor.py:156} INFO - Started process (PID=161) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:16:49.816+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:16:49.819+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:16:49.818+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:16:51.055+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:17:13.482+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:17:13.474+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:17:18.781+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:17:18.778+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:17:21.279+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 31.474 seconds
[2024-05-21T11:17:53.269+0000] {processor.py:156} INFO - Started process (PID=179) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:17:53.289+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:17:53.323+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:17:53.323+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:17:56.807+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:18:08.690+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:18:08.690+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:18:08.897+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:18:08.897+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:18:08.974+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 16.921 seconds
[2024-05-21T11:18:39.665+0000] {processor.py:156} INFO - Started process (PID=180) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:18:39.673+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:18:39.674+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:18:39.674+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:18:40.881+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:18:42.493+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:18:42.487+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:18:42.796+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:18:42.796+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:18:42.935+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 3.296 seconds
[2024-05-21T11:19:19.626+0000] {processor.py:156} INFO - Started process (PID=190) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:19:19.633+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:19:19.635+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:19:19.634+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:19:19.774+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:19:20.523+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:19:20.521+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:19:20.557+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:19:20.557+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:19:20.584+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 0.965 seconds
[2024-05-21T11:19:52.680+0000] {processor.py:156} INFO - Started process (PID=191) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:19:52.685+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:19:52.688+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:19:52.687+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:19:53.023+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:20:11.213+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:20:11.213+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:20:11.272+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:20:11.271+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:20:11.321+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 18.662 seconds
[2024-05-21T11:20:41.372+0000] {processor.py:156} INFO - Started process (PID=200) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:20:41.374+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:20:41.375+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:20:41.375+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:20:41.533+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:20:58.902+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:20:58.901+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:20:59.234+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:20:59.232+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:20:59.390+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 18.024 seconds
[2024-05-21T11:21:35.508+0000] {processor.py:156} INFO - Started process (PID=210) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:21:35.514+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:21:35.522+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:21:35.522+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:21:36.706+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:22:09.396+0000] {processor.py:181} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 177, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 161, in _handle_dag_file_processing
    callback_requests=callback_requests,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 783, in process_file
    dagbag.sync_to_db(processor_subdir=self._dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 632, in sync_to_db
    for attempt in run_with_db_retries(logger=self.log):
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 384, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 362, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 195, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 644, in sync_to_db
    serialize_errors.extend(_serialize_dag_capturing_errors(dag, session))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 618, in _serialize_dag_capturing_errors
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/serialized_dag.py", line 150, in write_dag
    (timezone.utcnow() - timedelta(seconds=min_update_interval)) < cls.last_updated,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2810, in first
    return self.limit(1)._iter().first()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2897, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1530, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3197, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3276, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3247, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2101, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-05-21T11:25:09.005+0000] {processor.py:156} INFO - Started process (PID=34) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:25:09.009+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:25:09.010+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:25:09.009+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:25:09.066+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:25:09.178+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:25:09.177+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:25:09.671+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:25:09.671+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:25:09.692+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 0.693 seconds
[2024-05-21T11:25:41.441+0000] {processor.py:156} INFO - Started process (PID=45) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:25:41.464+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:25:41.531+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:25:41.507+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:25:41.892+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:26:12.882+0000] {processor.py:181} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 177, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 161, in _handle_dag_file_processing
    callback_requests=callback_requests,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 783, in process_file
    dagbag.sync_to_db(processor_subdir=self._dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 632, in sync_to_db
    for attempt in run_with_db_retries(logger=self.log):
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 384, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 362, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 195, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 644, in sync_to_db
    serialize_errors.extend(_serialize_dag_capturing_errors(dag, session))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 618, in _serialize_dag_capturing_errors
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/serialized_dag.py", line 150, in write_dag
    (timezone.utcnow() - timedelta(seconds=min_update_interval)) < cls.last_updated,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2810, in first
    return self.limit(1)._iter().first()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2897, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1530, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3197, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3276, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3247, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2101, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-05-21T11:26:55.113+0000] {processor.py:156} INFO - Started process (PID=46) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:26:55.133+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:26:55.139+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:26:55.139+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:26:55.373+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:27:26.032+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:27:26.029+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:27:26.117+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:27:26.114+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:27:26.190+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 33.411 seconds
[2024-05-21T11:27:57.046+0000] {processor.py:156} INFO - Started process (PID=56) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:27:57.049+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:27:57.054+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:27:57.054+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:28:00.214+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:28:00.278+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:28:00.278+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:28:00.308+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:28:00.307+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:28:00.327+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 3.291 seconds
[2024-05-21T11:28:31.253+0000] {processor.py:156} INFO - Started process (PID=66) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:28:31.257+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:28:31.262+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:28:31.261+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:28:33.925+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:28:34.229+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:28:34.229+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:28:34.266+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:28:34.266+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:28:34.295+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 3.059 seconds
[2024-05-21T11:29:11.182+0000] {processor.py:156} INFO - Started process (PID=75) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:29:11.185+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:29:11.185+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:29:11.185+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:29:11.616+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:29:23.376+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:29:23.376+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:29:23.451+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:29:23.451+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:29:23.558+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 12.379 seconds
[2024-05-21T11:29:55.802+0000] {processor.py:156} INFO - Started process (PID=85) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:29:55.803+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:29:55.808+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:29:55.807+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:29:56.027+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:29:56.795+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:29:56.793+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:29:57.756+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:29:57.754+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:29:58.059+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 2.293 seconds
[2024-05-21T11:30:29.434+0000] {processor.py:156} INFO - Started process (PID=95) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:30:29.449+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:30:29.958+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:30:29.957+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:30:31.697+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:30:43.927+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:30:43.921+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:30:44.202+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:30:44.200+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:30:44.347+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 14.932 seconds
[2024-05-21T11:31:20.407+0000] {processor.py:156} INFO - Started process (PID=113) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:31:20.416+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:31:20.437+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:31:20.435+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:31:20.886+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:31:21.609+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:31:21.609+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:31:21.747+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:31:21.742+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:31:21.932+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 1.615 seconds
[2024-05-21T11:31:52.272+0000] {processor.py:156} INFO - Started process (PID=114) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:31:52.281+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:31:52.282+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:31:52.282+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:31:54.537+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:32:02.436+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:32:02.433+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:32:02.531+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:32:02.531+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:32:02.585+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 10.323 seconds
[2024-05-21T11:32:33.099+0000] {processor.py:156} INFO - Started process (PID=124) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:32:33.107+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:32:33.126+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:32:33.115+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:32:35.969+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:32:49.286+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:32:49.279+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:32:49.678+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:32:49.676+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:32:49.967+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 16.901 seconds
[2024-05-21T11:33:20.345+0000] {processor.py:156} INFO - Started process (PID=134) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:33:20.349+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:33:20.351+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:33:20.351+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:33:21.002+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:33:26.863+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:33:26.862+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:33:26.971+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:33:26.971+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:33:27.022+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 6.694 seconds
[2024-05-21T11:35:05.341+0000] {processor.py:156} INFO - Started process (PID=34) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:35:05.342+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:35:05.343+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:35:05.343+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:35:05.377+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:35:05.423+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:35:05.423+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:35:05.597+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:35:05.597+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:35:05.640+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 0.301 seconds
[2024-05-21T11:35:37.341+0000] {processor.py:156} INFO - Started process (PID=44) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:35:37.374+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:35:37.390+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:35:37.390+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:35:39.770+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:35:59.436+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:35:59.436+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:35:59.477+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:35:59.477+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:35:59.502+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 22.240 seconds
[2024-05-21T11:36:32.230+0000] {processor.py:156} INFO - Started process (PID=54) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:36:32.239+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:36:32.247+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:36:32.247+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:36:32.645+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:37:44.838+0000] {processor.py:156} INFO - Started process (PID=55) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:37:44.842+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:37:44.854+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:37:44.854+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:37:46.346+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:38:06.142+0000] {processor.py:156} INFO - Started process (PID=66) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:38:06.144+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T11:38:06.147+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:38:06.147+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:38:06.259+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T11:38:07.550+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:38:07.549+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T11:38:07.611+0000] {logging_mixin.py:117} INFO - [2024-05-21T11:38:07.611+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T11:38:07.648+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 1.508 seconds
[2024-05-21T15:28:45.290+0000] {processor.py:156} INFO - Started process (PID=38) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:28:45.293+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T15:28:45.295+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:28:45.295+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:28:45.431+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:28:48.394+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:28:48.394+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T15:28:48.438+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:28:48.438+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T15:28:48.481+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 3.194 seconds
[2024-05-21T15:29:27.046+0000] {processor.py:156} INFO - Started process (PID=52) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:29:27.051+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T15:29:27.173+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:29:27.061+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:29:27.715+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:29:45.613+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:29:45.610+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T15:29:46.454+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:29:46.454+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T15:29:46.505+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 19.520 seconds
[2024-05-21T15:30:22.487+0000] {processor.py:156} INFO - Started process (PID=66) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:30:22.498+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T15:30:22.507+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:30:22.506+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:30:25.258+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:33:38.134+0000] {processor.py:156} INFO - Started process (PID=78) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:33:38.146+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T15:33:38.149+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:33:38.149+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:33:38.572+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:34:21.345+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:34:21.343+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T15:34:21.652+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:34:21.650+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T15:34:21.756+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 43.648 seconds
[2024-05-21T15:34:52.878+0000] {processor.py:156} INFO - Started process (PID=103) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:34:52.921+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T15:34:52.925+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:34:52.924+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:34:53.246+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:34:53.860+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:34:53.859+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T15:34:53.942+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:34:53.940+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T15:34:54.042+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 1.190 seconds
[2024-05-21T15:35:24.122+0000] {processor.py:156} INFO - Started process (PID=107) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:35:24.386+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T15:35:24.401+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:35:24.400+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:35:25.046+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:35:41.279+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:35:41.273+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T15:35:41.688+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:35:41.685+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T15:35:41.765+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 17.654 seconds
[2024-05-21T15:36:22.444+0000] {processor.py:156} INFO - Started process (PID=121) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:36:22.448+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T15:36:22.449+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:36:22.449+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:36:22.808+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:36:59.319+0000] {processor.py:181} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 177, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 161, in _handle_dag_file_processing
    callback_requests=callback_requests,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 783, in process_file
    dagbag.sync_to_db(processor_subdir=self._dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 632, in sync_to_db
    for attempt in run_with_db_retries(logger=self.log):
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 384, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 362, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 195, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 644, in sync_to_db
    serialize_errors.extend(_serialize_dag_capturing_errors(dag, session))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 618, in _serialize_dag_capturing_errors
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/serialized_dag.py", line 150, in write_dag
    (timezone.utcnow() - timedelta(seconds=min_update_interval)) < cls.last_updated,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2810, in first
    return self.limit(1)._iter().first()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2897, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1530, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3197, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3276, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3247, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2101, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-05-21T15:37:35.638+0000] {processor.py:156} INFO - Started process (PID=128) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:37:35.640+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T15:37:35.642+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:37:35.641+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:37:35.848+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:38:03.015+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:38:03.015+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T15:38:03.137+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:38:03.136+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T15:38:03.257+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 27.626 seconds
[2024-05-21T15:38:33.341+0000] {processor.py:156} INFO - Started process (PID=144) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:38:33.343+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T15:38:33.344+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:38:33.343+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:38:34.336+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:38:41.318+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:38:41.318+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T15:38:41.405+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:38:41.404+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T15:38:41.435+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 8.099 seconds
[2024-05-21T15:39:23.029+0000] {processor.py:156} INFO - Started process (PID=159) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:39:23.035+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T15:39:23.036+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:39:23.035+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:39:26.288+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:40:54.050+0000] {processor.py:156} INFO - Started process (PID=173) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:40:54.062+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T15:40:54.071+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:40:54.067+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:40:54.321+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:40:54.714+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:40:54.714+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T15:40:54.893+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:40:54.889+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-19T21:00:00+00:00, run_after=2024-05-20T21:00:00+00:00
[2024-05-21T15:40:55.091+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 1.066 seconds
[2024-05-21T15:42:55.688+0000] {processor.py:156} INFO - Started process (PID=176) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:42:55.695+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T15:42:55.702+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:42:55.701+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:42:55.932+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:43:19.263+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:43:19.263+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T15:43:19.500+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:43:19.500+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-20T21:00:00+00:00, run_after=2024-05-21T21:00:00+00:00
[2024-05-21T15:43:19.611+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 23.975 seconds
[2024-05-21T15:43:58.739+0000] {processor.py:156} INFO - Started process (PID=193) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:43:58.743+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T15:43:58.744+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:43:58.744+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:43:58.985+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:44:33.577+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:44:33.571+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T15:44:33.720+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:44:33.719+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-20T21:00:00+00:00, run_after=2024-05-21T21:00:00+00:00
[2024-05-21T15:44:33.856+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 35.122 seconds
[2024-05-21T15:45:04.434+0000] {processor.py:156} INFO - Started process (PID=216) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:45:04.436+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T15:45:04.436+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:45:04.436+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:45:04.481+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:45:04.599+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:45:04.599+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T15:45:04.627+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:45:04.627+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-20T21:00:00+00:00, run_after=2024-05-21T21:00:00+00:00
[2024-05-21T15:45:04.646+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 0.214 seconds
[2024-05-21T15:45:35.210+0000] {processor.py:156} INFO - Started process (PID=221) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:45:35.217+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T15:45:35.218+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:45:35.218+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:45:35.451+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:45:49.143+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:45:49.142+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T15:45:49.238+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:45:49.238+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-20T21:00:00+00:00, run_after=2024-05-21T21:00:00+00:00
[2024-05-21T15:45:49.308+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 14.104 seconds
[2024-05-21T15:46:27.953+0000] {processor.py:156} INFO - Started process (PID=237) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:46:27.981+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T15:46:27.995+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:46:27.995+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:46:29.694+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:46:35.901+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:46:35.901+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T15:46:36.017+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:46:36.015+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-20T21:00:00+00:00, run_after=2024-05-21T21:00:00+00:00
[2024-05-21T15:46:36.090+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 8.179 seconds
[2024-05-21T15:49:56.438+0000] {processor.py:156} INFO - Started process (PID=242) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:49:56.439+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T15:49:56.441+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:49:56.440+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:49:56.804+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:49:57.466+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:49:57.465+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T15:49:57.726+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:49:57.724+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-20T21:00:00+00:00, run_after=2024-05-21T21:00:00+00:00
[2024-05-21T15:49:57.787+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 1.356 seconds
[2024-05-21T15:50:33.245+0000] {processor.py:156} INFO - Started process (PID=256) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:50:33.251+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T15:50:33.252+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:50:33.251+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:50:34.328+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:53:21.071+0000] {processor.py:156} INFO - Started process (PID=261) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:53:21.077+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T15:53:21.078+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:53:21.078+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:53:21.162+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:53:21.240+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:53:21.240+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T15:53:21.280+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:53:21.280+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-20T21:00:00+00:00, run_after=2024-05-21T21:00:00+00:00
[2024-05-21T15:53:21.303+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 0.235 seconds
[2024-05-21T15:54:49.407+0000] {processor.py:156} INFO - Started process (PID=266) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:54:49.434+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T15:54:49.471+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:54:49.453+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:54:52.353+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:54:56.590+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:54:56.589+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T15:54:57.234+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:54:57.217+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-20T21:00:00+00:00, run_after=2024-05-21T21:00:00+00:00
[2024-05-21T15:54:57.777+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 8.579 seconds
[2024-05-21T15:55:30.834+0000] {processor.py:156} INFO - Started process (PID=279) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:55:30.839+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T15:55:30.847+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:55:30.847+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:55:31.081+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:55:48.232+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:55:48.231+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T15:55:48.306+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:55:48.306+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-20T21:00:00+00:00, run_after=2024-05-21T21:00:00+00:00
[2024-05-21T15:55:48.371+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 17.546 seconds
[2024-05-21T15:56:30.796+0000] {processor.py:156} INFO - Started process (PID=284) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:56:30.858+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T15:56:31.636+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:56:31.628+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:56:33.421+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:56:50.106+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:56:50.103+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T15:56:50.198+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:56:50.191+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-20T21:00:00+00:00, run_after=2024-05-21T21:00:00+00:00
[2024-05-21T15:56:50.265+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 19.497 seconds
[2024-05-21T15:57:26.091+0000] {processor.py:156} INFO - Started process (PID=289) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:57:26.095+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T15:57:26.097+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:57:26.096+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:57:26.315+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:57:45.641+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:57:45.637+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T15:57:48.116+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:57:48.111+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-20T21:00:00+00:00, run_after=2024-05-21T21:00:00+00:00
[2024-05-21T15:57:49.475+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 23.391 seconds
[2024-05-21T15:58:19.649+0000] {processor.py:156} INFO - Started process (PID=312) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:58:19.652+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T15:58:19.654+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:58:19.654+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:58:20.460+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:58:52.819+0000] {processor.py:181} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 177, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 161, in _handle_dag_file_processing
    callback_requests=callback_requests,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 783, in process_file
    dagbag.sync_to_db(processor_subdir=self._dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 632, in sync_to_db
    for attempt in run_with_db_retries(logger=self.log):
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 384, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 362, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 195, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 644, in sync_to_db
    serialize_errors.extend(_serialize_dag_capturing_errors(dag, session))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 618, in _serialize_dag_capturing_errors
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/serialized_dag.py", line 150, in write_dag
    (timezone.utcnow() - timedelta(seconds=min_update_interval)) < cls.last_updated,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2810, in first
    return self.limit(1)._iter().first()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2897, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1530, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3197, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3276, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3247, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2101, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-05-21T15:59:24.491+0000] {processor.py:156} INFO - Started process (PID=328) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:59:24.494+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T15:59:24.495+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:59:24.494+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:59:26.057+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T15:59:34.652+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:59:34.651+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T15:59:34.842+0000] {logging_mixin.py:117} INFO - [2024-05-21T15:59:34.841+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-20T21:00:00+00:00, run_after=2024-05-21T21:00:00+00:00
[2024-05-21T15:59:35.009+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 10.533 seconds
[2024-05-21T16:00:22.441+0000] {processor.py:156} INFO - Started process (PID=352) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:00:22.443+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T16:00:22.443+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:00:22.443+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:00:22.680+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:00:54.818+0000] {processor.py:181} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 177, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 161, in _handle_dag_file_processing
    callback_requests=callback_requests,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 783, in process_file
    dagbag.sync_to_db(processor_subdir=self._dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 632, in sync_to_db
    for attempt in run_with_db_retries(logger=self.log):
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 384, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 362, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 195, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 644, in sync_to_db
    serialize_errors.extend(_serialize_dag_capturing_errors(dag, session))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 618, in _serialize_dag_capturing_errors
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/serialized_dag.py", line 150, in write_dag
    (timezone.utcnow() - timedelta(seconds=min_update_interval)) < cls.last_updated,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2810, in first
    return self.limit(1)._iter().first()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2897, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1530, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3197, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3276, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3247, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2101, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-05-21T16:01:26.994+0000] {processor.py:156} INFO - Started process (PID=359) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:01:27.005+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T16:01:27.043+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:01:27.042+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:01:27.366+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:01:28.522+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:01:28.506+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T16:01:29.123+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:01:29.119+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-20T21:00:00+00:00, run_after=2024-05-21T21:00:00+00:00
[2024-05-21T16:01:29.847+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 2.856 seconds
[2024-05-21T16:02:00.958+0000] {processor.py:156} INFO - Started process (PID=382) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:02:00.961+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T16:02:00.962+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:02:00.962+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:02:03.235+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:02:26.384+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:02:26.381+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T16:02:28.020+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:02:28.014+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-20T21:00:00+00:00, run_after=2024-05-21T21:00:00+00:00
[2024-05-21T16:02:29.073+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 28.118 seconds
[2024-05-21T16:02:59.324+0000] {processor.py:156} INFO - Started process (PID=406) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:02:59.326+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T16:02:59.327+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:02:59.327+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:02:59.994+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:03:16.252+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:03:16.252+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T16:03:16.310+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:03:16.309+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-20T21:00:00+00:00, run_after=2024-05-21T21:00:00+00:00
[2024-05-21T16:03:16.361+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 17.042 seconds
[2024-05-21T16:03:46.590+0000] {processor.py:156} INFO - Started process (PID=412) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:03:46.592+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T16:03:46.592+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:03:46.592+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:03:46.629+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:03:46.701+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:03:46.700+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T16:03:46.733+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:03:46.732+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-20T21:00:00+00:00, run_after=2024-05-21T21:00:00+00:00
[2024-05-21T16:03:46.756+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 0.168 seconds
[2024-05-21T16:04:17.037+0000] {processor.py:156} INFO - Started process (PID=426) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:04:17.052+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T16:04:17.068+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:04:17.064+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:04:18.614+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:04:19.837+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:04:19.836+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T16:04:19.922+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:04:19.919+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-20T21:00:00+00:00, run_after=2024-05-21T21:00:00+00:00
[2024-05-21T16:04:19.968+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 2.941 seconds
[2024-05-21T16:04:50.555+0000] {processor.py:156} INFO - Started process (PID=439) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:04:50.556+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T16:04:50.557+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:04:50.557+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:04:51.237+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:05:13.846+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:05:13.841+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T16:05:14.199+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:05:14.197+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-20T21:00:00+00:00, run_after=2024-05-21T21:00:00+00:00
[2024-05-21T16:05:14.610+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 24.060 seconds
[2024-05-21T16:06:23.036+0000] {processor.py:156} INFO - Started process (PID=457) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:06:23.040+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T16:06:23.046+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:06:23.046+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:06:24.204+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:06:57.666+0000] {processor.py:181} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 177, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 161, in _handle_dag_file_processing
    callback_requests=callback_requests,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 783, in process_file
    dagbag.sync_to_db(processor_subdir=self._dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 632, in sync_to_db
    for attempt in run_with_db_retries(logger=self.log):
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 384, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 362, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 195, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 644, in sync_to_db
    serialize_errors.extend(_serialize_dag_capturing_errors(dag, session))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 618, in _serialize_dag_capturing_errors
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/serialized_dag.py", line 150, in write_dag
    (timezone.utcnow() - timedelta(seconds=min_update_interval)) < cls.last_updated,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2810, in first
    return self.limit(1)._iter().first()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2897, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1530, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3197, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3276, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3247, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2101, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-05-21T16:07:28.288+0000] {processor.py:156} INFO - Started process (PID=471) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:07:28.296+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T16:07:28.298+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:07:28.297+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:07:28.386+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:07:48.793+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:07:48.792+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T16:07:48.857+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:07:48.857+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-20T21:00:00+00:00, run_after=2024-05-21T21:00:00+00:00
[2024-05-21T16:07:48.935+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 20.655 seconds
[2024-05-21T16:08:31.035+0000] {processor.py:156} INFO - Started process (PID=498) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:08:31.046+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T16:08:31.048+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:08:31.047+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:08:31.154+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:08:31.297+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:08:31.297+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T16:08:31.356+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:08:31.356+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-20T21:00:00+00:00, run_after=2024-05-21T21:00:00+00:00
[2024-05-21T16:08:31.605+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 0.578 seconds
[2024-05-21T16:09:10.649+0000] {processor.py:156} INFO - Started process (PID=512) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:09:10.672+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T16:09:10.672+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:09:10.672+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:09:10.804+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:09:11.723+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:09:11.722+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T16:09:12.409+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:09:12.409+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-20T21:00:00+00:00, run_after=2024-05-21T21:00:00+00:00
[2024-05-21T16:09:12.559+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 1.947 seconds
[2024-05-21T16:10:00.614+0000] {processor.py:156} INFO - Started process (PID=528) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:10:00.638+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T16:10:00.643+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:10:00.643+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:10:01.372+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:20:43.222+0000] {processor.py:156} INFO - Started process (PID=37) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:20:43.223+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T16:20:43.225+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:20:43.225+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:20:43.329+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:20:47.660+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:20:47.660+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T16:20:47.695+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:20:47.694+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-20T21:00:00+00:00, run_after=2024-05-21T21:00:00+00:00
[2024-05-21T16:20:47.734+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 4.514 seconds
[2024-05-21T16:21:34.260+0000] {processor.py:156} INFO - Started process (PID=59) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:21:34.263+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T16:21:34.266+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:21:34.266+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:21:34.494+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:21:39.738+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:21:39.737+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2024-05-21T16:21:39.773+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:21:39.772+0000] {dag.py:3328} INFO - Setting next_dagrun for airflow_first_dag to 2024-05-20T21:00:00+00:00, run_after=2024-05-21T21:00:00+00:00
[2024-05-21T16:21:39.798+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/airflow_first_dag.py took 5.590 seconds
[2024-05-21T16:22:46.308+0000] {processor.py:156} INFO - Started process (PID=82) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:22:46.323+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T16:22:46.332+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:22:46.331+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:22:46.670+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:23:24.040+0000] {processor.py:181} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 177, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 161, in _handle_dag_file_processing
    callback_requests=callback_requests,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 783, in process_file
    dagbag.sync_to_db(processor_subdir=self._dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 632, in sync_to_db
    for attempt in run_with_db_retries(logger=self.log):
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 384, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 362, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 195, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 644, in sync_to_db
    serialize_errors.extend(_serialize_dag_capturing_errors(dag, session))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 618, in _serialize_dag_capturing_errors
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/serialized_dag.py", line 150, in write_dag
    (timezone.utcnow() - timedelta(seconds=min_update_interval)) < cls.last_updated,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2810, in first
    return self.limit(1)._iter().first()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2897, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1530, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3197, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3276, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3247, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2101, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-05-21T16:24:06.462+0000] {processor.py:156} INFO - Started process (PID=90) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:24:06.465+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T16:24:06.465+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:24:06.465+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:24:06.600+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:24:42.365+0000] {processor.py:181} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 177, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 161, in _handle_dag_file_processing
    callback_requests=callback_requests,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 783, in process_file
    dagbag.sync_to_db(processor_subdir=self._dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 632, in sync_to_db
    for attempt in run_with_db_retries(logger=self.log):
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 384, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 362, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 195, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 644, in sync_to_db
    serialize_errors.extend(_serialize_dag_capturing_errors(dag, session))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 618, in _serialize_dag_capturing_errors
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/serialized_dag.py", line 150, in write_dag
    (timezone.utcnow() - timedelta(seconds=min_update_interval)) < cls.last_updated,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2810, in first
    return self.limit(1)._iter().first()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2897, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1530, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3197, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3276, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3247, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2101, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-05-21T16:25:28.815+0000] {processor.py:156} INFO - Started process (PID=97) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:25:28.817+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T16:25:28.820+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:25:28.819+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:25:29.503+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:26:00.588+0000] {processor.py:181} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 177, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 161, in _handle_dag_file_processing
    callback_requests=callback_requests,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 783, in process_file
    dagbag.sync_to_db(processor_subdir=self._dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 632, in sync_to_db
    for attempt in run_with_db_retries(logger=self.log):
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 384, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 362, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 195, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 644, in sync_to_db
    serialize_errors.extend(_serialize_dag_capturing_errors(dag, session))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 618, in _serialize_dag_capturing_errors
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/serialized_dag.py", line 150, in write_dag
    (timezone.utcnow() - timedelta(seconds=min_update_interval)) < cls.last_updated,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2810, in first
    return self.limit(1)._iter().first()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2897, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1530, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3197, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3276, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3247, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2101, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-05-21T16:26:43.929+0000] {processor.py:156} INFO - Started process (PID=103) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:26:43.932+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T16:26:43.933+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:26:43.932+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:26:44.520+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:27:18.780+0000] {processor.py:181} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 177, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 161, in _handle_dag_file_processing
    callback_requests=callback_requests,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 783, in process_file
    dagbag.sync_to_db(processor_subdir=self._dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 632, in sync_to_db
    for attempt in run_with_db_retries(logger=self.log):
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 384, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 362, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 195, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 644, in sync_to_db
    serialize_errors.extend(_serialize_dag_capturing_errors(dag, session))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 618, in _serialize_dag_capturing_errors
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/serialized_dag.py", line 150, in write_dag
    (timezone.utcnow() - timedelta(seconds=min_update_interval)) < cls.last_updated,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2810, in first
    return self.limit(1)._iter().first()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2897, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1530, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3197, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3276, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3247, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2101, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-05-21T16:27:59.865+0000] {processor.py:156} INFO - Started process (PID=108) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:27:59.870+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T16:27:59.873+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:27:59.872+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:28:00.064+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:28:31.086+0000] {processor.py:181} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 177, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 161, in _handle_dag_file_processing
    callback_requests=callback_requests,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 783, in process_file
    dagbag.sync_to_db(processor_subdir=self._dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 632, in sync_to_db
    for attempt in run_with_db_retries(logger=self.log):
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 384, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 362, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 195, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 644, in sync_to_db
    serialize_errors.extend(_serialize_dag_capturing_errors(dag, session))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 618, in _serialize_dag_capturing_errors
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/serialized_dag.py", line 150, in write_dag
    (timezone.utcnow() - timedelta(seconds=min_update_interval)) < cls.last_updated,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2810, in first
    return self.limit(1)._iter().first()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2897, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1530, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3197, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3276, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3247, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2101, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-05-21T16:29:38.003+0000] {processor.py:156} INFO - Started process (PID=114) to work on /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:29:38.007+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/airflow_first_dag.py for tasks to queue
[2024-05-21T16:29:38.008+0000] {logging_mixin.py:117} INFO - [2024-05-21T16:29:38.008+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_first_dag.py
[2024-05-21T16:29:38.426+0000] {processor.py:768} INFO - DAG(s) dict_keys(['airflow_first_dag']) retrieved from /opt/airflow/dags/airflow_first_dag.py
